name: "Deploy to CGC"
on:
  release:
    types: [released, edited]
jobs:
  cgc:
    runs-on: ubuntu-20.04
    name: "Deploy"
    steps:
      - uses: actions/checkout@v2
      - id: cgcdeploy
        uses: jordan-rash/cgc-go@v0.1.4
        with:
          file_location: "cgc/netbid.cwl"
          shortid: "stjude/netbid/netbid"
        env: 
          CGC_TOKEN: ${{ secrets.CGC_TOKEN }}
    
